"""status do paciente

Revision ID: 1f0f634a6fbf
Revises: 930bb21c1b90
Create Date: 2026-07-11 14:14:01.921044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0f634a6fbf'
down_revision: Union[str, None] = '930bb21c1b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('status', sa.String(), server_default='em_avaliacao', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'status')
    # ### end Alembic commands ###
