"""initial schema

Revision ID: 930bb21c1b90
Revises: 
Create Date: 2026-07-08 10:36:07.253468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930bb21c1b90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('plano', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('nome_mae', sa.String(), nullable=False),
    sa.Column('nome_pai', sa.String(), nullable=False),
    sa.Column('tem_irmaos', sa.Boolean(), nullable=False),
    sa.Column('nome_irmaos', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('data_inicio_nipwin', sa.Date(), nullable=True),
    sa.Column('faz_uso_medicamento', sa.Text(), nullable=False),
    sa.Column('consentimento_lgpd_assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_clinica_id'), 'pacientes', ['clinica_id'], unique=False)
    op.create_table('protocolos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolos_clinica_id'), 'protocolos', ['clinica_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_login_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinica_id', 'email', name='uq_usuarios_clinica_email')
    )
    op.create_index(op.f('ix_usuarios_clinica_id'), 'usuarios', ['clinica_id'], unique=False)
    op.create_table('anexos',
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('tipo_arquivo', sa.String(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('storage_ref', sa.String(), nullable=False),
    sa.Column('criado_por', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_clinica_id'), 'anexos', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_anexos_entidade_id'), 'anexos', ['entidade_id'], unique=False)
    op.create_table('caa_dados',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('usa_caa', sa.Boolean(), nullable=False),
    sa.Column('protocolo_aip_aplicado', sa.Boolean(), nullable=False),
    sa.Column('sistema_ajustado', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paciente_id')
    )
    op.create_index(op.f('ix_caa_dados_clinica_id'), 'caa_dados', ['clinica_id'], unique=False)
    op.create_table('evolucoes',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evolucoes_clinica_id'), 'evolucoes', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_evolucoes_paciente_id'), 'evolucoes', ['paciente_id'], unique=False)
    op.create_table('logs_acesso',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.UUID(), nullable=False),
    sa.Column('ip_origem', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_acesso_clinica_id'), 'logs_acesso', ['clinica_id'], unique=False)
    op.create_table('profissionais_caso',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profissionais_caso_clinica_id'), 'profissionais_caso', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_profissionais_caso_paciente_id'), 'profissionais_caso', ['paciente_id'], unique=False)
    op.create_table('protocolos_paciente',
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('protocolo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_realizacao', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocolos_paciente_clinica_id'), 'protocolos_paciente', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_protocolos_paciente_paciente_id'), 'protocolos_paciente', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_protocolos_paciente_protocolo_id'), 'protocolos_paciente', ['protocolo_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinica_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado', sa.Boolean(), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_clinica_id'), 'refresh_tokens', ['clinica_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_clinica_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_protocolos_paciente_protocolo_id'), table_name='protocolos_paciente')
    op.drop_index(op.f('ix_protocolos_paciente_paciente_id'), table_name='protocolos_paciente')
    op.drop_index(op.f('ix_protocolos_paciente_clinica_id'), table_name='protocolos_paciente')
    op.drop_table('protocolos_paciente')
    op.drop_index(op.f('ix_profissionais_caso_paciente_id'), table_name='profissionais_caso')
    op.drop_index(op.f('ix_profissionais_caso_clinica_id'), table_name='profissionais_caso')
    op.drop_table('profissionais_caso')
    op.drop_index(op.f('ix_logs_acesso_clinica_id'), table_name='logs_acesso')
    op.drop_table('logs_acesso')
    op.drop_index(op.f('ix_evolucoes_paciente_id'), table_name='evolucoes')
    op.drop_index(op.f('ix_evolucoes_clinica_id'), table_name='evolucoes')
    op.drop_table('evolucoes')
    op.drop_index(op.f('ix_caa_dados_clinica_id'), table_name='caa_dados')
    op.drop_table('caa_dados')
    op.drop_index(op.f('ix_anexos_entidade_id'), table_name='anexos')
    op.drop_index(op.f('ix_anexos_clinica_id'), table_name='anexos')
    op.drop_table('anexos')
    op.drop_index(op.f('ix_usuarios_clinica_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_protocolos_clinica_id'), table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_pacientes_clinica_id'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('clinicas')
    # ### end Alembic commands ###
