"""status e audio_ref em evolucoes

Revision ID: c35f0e370575
Revises: 1f0f634a6fbf
Create Date: 2026-07-17 10:16:00.985596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35f0e370575'
down_revision: Union[str, None] = '1f0f634a6fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evolucoes', sa.Column('status', sa.String(), server_default='confirmada', nullable=False))
    op.add_column('evolucoes', sa.Column('audio_ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evolucoes', 'audio_ref')
    op.drop_column('evolucoes', 'status')
    # ### end Alembic commands ###
